# manifest hydra folder
hydra:
  output_subdir: hydra

device: CUDA_IF_AVAILABLE  # this default is handled in a special decorator, can be overridden
device_type: ???     # this is set in the same decorator based on the device; this should NOT be overridden

# TODO seed

dataset:
  _target_: data.MarioCSVDataset
  csv_path: v1--processed.csv
  number_of_other_robots: 2
  time_span: 5

tokenizer:
  _target_: tokenizer.Tokenizer
  x_min: -4500.0
  y_min: -3000.0
  x_max: 4500.0
  y_max: 3000.0
  x_buckets: 50
  y_buckets: 30

vocab_size: ???   # this is set in a special decorator based on the number of buckets, do NOT override

training:
  data_split: 0.95
  batch_size: 64  # partiamo molto ottimisti, vedremo poi quando ci esplode la memoria

eval:
  batch_size: ${training.batch_size}
